// src/pages/FeedbackFormModal.tsx
import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  Grid,
  CircularProgress,
  Alert,
  AlertTitle,
  MenuItem,
  Select,
  FormControl,
  InputLabel,
} from '@mui/material';
import { SelectChangeEvent } from '@mui/material/Select';

import {
  FeedbackItem,
  FeedbackType,
  FeedbackPriority,
  SentimentPolarity,
} from '../types/feedback'; // Ensure this path is correct

// Shape of data expected by the add function in FeedbackDashboard.tsx
// Omits properties generated by the backend.
type NewFeedbackItem = Omit<
  FeedbackItem,
  'id' | 'submissionDate' | 'status' | 'lastUpdated'
>;

interface FeedbackFormModalProps {
  open: boolean;
  onClose: () => void;
  onSubmit: (newItem: NewFeedbackItem) => Promise<void>;
}

const FeedbackFormModal: React.FC<FeedbackFormModalProps> = ({
  open,
  onClose,
  onSubmit,
}) => {
  const initialFormState: NewFeedbackItem = {
    title: '',
    description: '',
    type: FeedbackType.ConstituentGrievance, // Default type
    priority: FeedbackPriority.Medium, // Default priority
    source: '',
    county: '',
    constituency: '',
    ward: '',
    locationDetails: '',
    contactMethod: '',
    contactInfo: '',
    assignedTo: '',
    sentiment: null,
    tags: [],
    followUpDate: '',
    resolutionDetails: '',
  };

  const [formData, setFormData] = useState<NewFeedbackItem>(initialFormState);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [submitSuccess, setSubmitSuccess] = useState<boolean>(false);

  // Reset form state when the modal opens
  useEffect(() => {
    if (open) {
      setFormData(initialFormState);
      setSubmitError(null);
      setSubmitSuccess(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    setSubmitError(null);
  };

  // For MUI <Select>, use SelectChangeEvent and not the native ChangeEvent<HTMLSelectElement>
  const handleSelectChange = (e: SelectChangeEvent<string>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      // Map empty string to null for sentiment, otherwise store the string value
      [name as string]:
        name === 'sentiment' && value === '' ? null : (value as any),
    }));
    setSubmitError(null);
  };

  const handleTagsChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const tagsInput = e.target.value;
    setFormData((prev) => ({
      ...prev,
      tags: tagsInput
        .split(',')
        .map((tag) => tag.trim())
        .filter((tag) => tag !== ''),
    }));
    setSubmitError(null);
  };

  const handleSubmit = async () => {
    setIsSubmitting(true);
    setSubmitError(null);
    setSubmitSuccess(false);
    try {
      await onSubmit(formData);
      setSubmitSuccess(true);
      setTimeout(() => {
        onClose();
      }, 1500);
    } catch (err: any) {
      setSubmitError(err?.message || 'Failed to submit new engagement.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth>
      <DialogTitle>Log New Constituent Engagement</DialogTitle>
      <DialogContent dividers>
        {submitError && (
          <Alert severity="error" sx={{ mb: 2 }}>
            <AlertTitle>Submission Error</AlertTitle>
            {submitError}
          </Alert>
        )}
        {submitSuccess && (
          <Alert severity="success" sx={{ mb: 2 }}>
            <AlertTitle>Success</AlertTitle>
            New engagement logged successfully!
          </Alert>
        )}
        <Grid container spacing={2}>
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Title (e.g., Road Repair Request, Positive Rally Feedback)"
              name="title"
              value={formData.title}
              onChange={handleChange}
              margin="normal"
              required
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Description (Detailed account of the interaction)"
              name="description"
              value={formData.description}
              onChange={handleChange}
              margin="normal"
              multiline
              rows={4}
              required
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <FormControl fullWidth margin="normal" variant="outlined">
              <InputLabel id="type-label">Engagement Type</InputLabel>
              <Select
                labelId="type-label"
                label="Engagement Type"
                name="type"
                value={formData.type as unknown as string}
                onChange={handleSelectChange}
                required
              >
                {(Object.values(FeedbackType) as string[]).map((type) => (
                  <MenuItem key={type} value={type}>
                    {type}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} sm={6}>
            <FormControl fullWidth margin="normal" variant="outlined">
              <InputLabel id="priority-label">Priority</InputLabel>
              <Select
                labelId="priority-label"
                label="Priority"
                name="priority"
                value={formData.priority as unknown as string}
                onChange={handleSelectChange}
                required
              >
                {(Object.values(FeedbackPriority) as string[]).map(
                  (priority) => (
                    <MenuItem key={priority} value={priority}>
                      {priority}
                    </MenuItem>
                  )
                )}
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Source (e.g., Online Form, Phone Call, Field Report)"
              name="source"
              value={formData.source}
              onChange={handleChange}
              margin="normal"
              required
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="County"
              name="county"
              value={formData.county}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Constituency"
              name="constituency"
              value={formData.constituency}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Ward"
              name="ward"
              value={formData.ward}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Specific Location Details (e.g., 'Near Wote ACK Church')"
              name="locationDetails"
              value={formData.locationDetails}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Preferred Contact Method"
              name="contactMethod"
              value={formData.contactMethod}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Contact Information (Email or Phone)"
              name="contactInfo"
              value={formData.contactInfo}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Assigned To (e.g., 'John Doe', 'Field Team')"
              name="assignedTo"
              value={formData.assignedTo}
              onChange={handleChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <FormControl fullWidth margin="normal" variant="outlined">
              <InputLabel id="sentiment-label">Sentiment</InputLabel>
              <Select
                labelId="sentiment-label"
                label="Sentiment"
                name="sentiment"
                value={(formData.sentiment ?? '') as unknown as string}
                onChange={handleSelectChange}
              >
                <MenuItem value="">
                  <em>None</em>
                </MenuItem>
                {(Object.values(SentimentPolarity) as string[]).map(
                  (sentiment) => (
                    <MenuItem key={sentiment} value={sentiment}>
                      {sentiment}
                    </MenuItem>
                  )
                )}
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Tags (comma-separated, e.g., 'Infrastructure, Roads, Water')"
              name="tags"
              value={formData.tags?.join(', ') || ''}
              onChange={handleTagsChange}
              margin="normal"
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Follow-up Date (Optional)"
              name="followUpDate"
              type="date"
              value={formData.followUpDate}
              onChange={handleChange}
              margin="normal"
              InputLabelProps={{
                shrink: true,
              }}
              variant="outlined"
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Resolution Details (Optional)"
              name="resolutionDetails"
              value={formData.resolutionDetails}
              onChange={handleChange}
              margin="normal"
              multiline
              rows={3}
              variant="outlined"
            />
          </Grid>
        </Grid>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} color="secondary" disabled={isSubmitting}>
          Cancel
        </Button>
        <Button
          onClick={handleSubmit}
          color="primary"
          variant="contained"
          disabled={isSubmitting}
        >
          {isSubmitting ? <CircularProgress size={24} /> : 'Add Engagement'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default FeedbackFormModal;
